### ISSUE TITLE
log3 not working in Python3.8 at all

### ISSUE THREAD

**Issue by mjmurphy3** [orlandodiaz/log3#1]
The Python3.8 formatter does not like the arguments being passed from line 22 of config, see REPL output:

Python 3.8.3 (default, May 14 2020, 11:03:12) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from log3 import log
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/git/zone_inventory/venv/lib/python3.8/site-packages/log3/__init__.py", line 1, in <module>
    from .log import logger as log
  File "/home/username/git/zone_inventory/venv/lib/python3.8/site-packages/log3/log.py", line 31, in <module>
    config()
  File "/home/username/git/zone_inventory/venv/lib/python3.8/site-packages/log3/log.py", line 22, in config
    formatter = logging.Formatter(fmt, datefmt=date_fmt)
  File "/usr/lib/python3.8/logging/__init__.py", line 576, in __init__
    self._style.validate()
  File "/usr/lib/python3.8/logging/__init__.py", line 428, in validate
    if not self.validation_pattern.search(self._fmt):
TypeError: expected string or bytes-like object

**Comment by Demmenie** [comment]
This also seems to be causing issues in other applications that use log3. I traced this back from an unofficial Instagram API.
